Rails/Projekte/shooting_club/config/routes.rb
Rails.application.routes.draw do
	

  get 'analysis/index'
  get 'analysis/select'
  get 'analysis/calculate'
  delete 'events/loeschen'
  delete 'events/loeschenall'

  resources :groups do
  	get 'addnew' => 'groups#addnew'
  	post 'addcreate' => 'groups#addcreate'
    delete 'deletem' => 'groups#deletem'
  end
	get 'auswertung' => 'events#indexwrong'
  resources :resumes
  resources :events do 
  	member do
  		get 'import'
  	end
 	end
 	root "marksmen#index"
 	resources :marksmen
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/Projekte/shooting_club/app/models/event.rb
class Event < ApplicationRecord

	def self.import(resume)
		ec = Encoding::Converter.new("ISO-8859-1", "UTF-8")
		file_path = "#{Rails.root}/public#{resume.attachment}"
		@post = []
		counter = 0
		counterer = 0
		datum = Time.new
		File.open(file_path, 'r') do |file|
			file.each do |rows|
				rows = ec.convert(rows)
				rows = rows.tr(",", ".")
				row = rows.split(" ; ")
				date = row[16].split(".")
				time = row[14].split(":")
				time[0] = time[0]
				datum = Time.new(date[2], date[1], date[0], time[0], time[1], time[2])
				
				if !Event.exists?(:time_date => datum, :shooting_range => row[3])
					Event.create(name: row[0], unknown0: row[1], unknown1: row[2], shooting_range: row[3], marksmen: row[4], unknown2: row[5], unknown3: row[6], shoot_number: row[7], value: row[8], unknown4: row[9], unknown5: row[10], unknown6: row[11], unknown7: row[12], unknown8: row[13], time_date: datum, unknown9: row[15], unknown10: row[17], unknown11: row[18])
					counterer = counterer+1
				else
					counter = counter+1
				end

			end
		end
		@post[0] = counter
		@post[1] = counterer
		@post
	end
end

Rails/Projekte/shooting_club/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]


  def import
    resume = Resume.find(params[:id])
    #@resumeid = resume.id
    @post = Event.import(resume)
  end
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  def indexwrong
    @events = Event.where( :marksmen => 0).paginate(:per_page => 20, :page => params[:page])
  end
  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def loeschenall
    Event.delete_all
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Alle Einträge wurden erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
end

def loeschen
    Event.where(:marksmen => 0).delete_all
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Alle fehlerhaften Einträge wurden erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :unknown0, :unknown1, :shooting_range, :marksmen, :unknown2, :unknown3, :shoot_number, :value, :unknown4, :unknown5, :unknown6, :unknown7, :unknown8, :time_date, :unknown9, :unknown10, :unknown11)
    end
end

Rails/Projekte/shooting_club/app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="medium-4 columns">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-4 columns">
    <%= f.label :shooting_range %>
    <%= f.number_field :shooting_range %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-4 columns">
    <%= f.label :marksmen %>
    <%= f.number_field :marksmen %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-4 columns">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-4 columns">
    <%= f.label "Teiler" %>
    <%= f.text_field :unknown7 %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-12 columns">
    <%= f.label :time_date %>
    <%= f.datetime_select :time_date %>
  </div>

  <div class="medium-12 columns">
  </div>
  
  <div class="actions medium-12 columns">
    <br><br>
    <%= f.submit 'Abschicken', class: "button primary" %>
  </div>
</div>
<% end %>

Rails/Projekte/shooting_club/app/views/events/edit.html.erb
<h1>Eintrag editieren:</h1>

<%= render 'form', event: @event %>

<%= link_to 'Zurück', events_path, class: "button small warning" %>

Rails/Projekte/shooting_club/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Einträge:</h1>
<br>
<br>

</div>
<div class="row">
  <div class="small-2 large-4 columns"><%= button_to 'Neuer Eintrag', new_event_path, method: :get, class: "button primary" %></div>
  <div class="small-4 large-4 columns"><%= button_to 'DB überprüfen', auswertung_path, method: :get, class: "button success" %></div>
  <div class="small-6 large-4 columns"><%= button_to 'Alle Löschen', events_loeschenall_path, method: :delete, data: { confirm: 'Willst du alle Einträge löschen?' }, class: "button alert" %></div>
</div>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Linie</th>
      <th>Schütze</th>
      <th>Wert</th>
      <th>Teiler</th>
      <th>Zeitpunkt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.shooting_range %></td>
        <td><%= event.marksmen %></td>
        <td><%= event.value %></td>
        <td><%= event.unknown7 %></td>
        <td><%= event.time_date.strftime("%d.%m.%Y %H:%M:%S Uhr") %></td>
        <td>
          <%= link_to 'Edit', edit_event_path(event), class: "button small secondary" %>
          <%= link_to 'Löschen', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "button small alert" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

Rails/Projekte/shooting_club/app/views/events/indexwrong.html.erb
<p id="notice"><%= notice %></p>

<h1>Fehlerhafte Einträge:</h1>

<div class="callout alert1">
  <h5>Achtung:</h5>
  <p>Bitte passen sie die Schützen ID der fehlerhaften Einträge an, damit sie die Auswertung vortführen können!</p>
</div>

<div class="row">
  <div class="large-3 columns">
  </div>
  <div class="large-6 columns">
    <div class="digg_pagination margin_allgemein">
      <%= will_paginate @marksmen, :container => false %>
    </div>
  </div>
  <div class="large-3 columns">

  </div>
</div>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Linie</th>
      <th>Schütze</th>
      <th></th>
      <th>Wert</th>
      <th>Teiler</th>
      <th>Zeitpunkt</th>
      <th><%= link_to 'Alle Löschen', events_loeschen_path, method: :delete, data: { confirm: 'Willst du alle fehlerhaften Einträge löschen?' }, class: "button alert" %></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.shooting_range %></td>
        <td style="">
          <%= form_for(event) do |f| %>
            <%= f.number_field :marksmen %>
        </td>
        <td style="">
            <%= f.submit 'Update', class: "button tiny success btn_form"%>
          <% end %>
        </td>
        <td><%= event.value %></td>
        <td><%= event.unknown7 %></td>
        <td><%= event.time_date.strftime("%d.%m.%Y %H:%M:%S Uhr") %></td>
        <td>
          <%= link_to 'Details', event, class: "button small warning" %>
          <%= link_to 'Edit', edit_event_path(event), class: "button small secondary" %>
          <%= link_to 'Löschen', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "button small alert" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @marksmen %>
  </div>
</div>

Rails/Projekte/shooting_club/app/views/events/new.html.erb
<h1>Neuer Eintrag:</h1>

<%= render 'form', event: @event %>

<%= link_to 'Zurück', events_path, class: "button small warning" %>

Rails/Projekte/shooting_club/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Shooting range:</strong>
  <%= @event.shooting_range %>
</p>

<p>
  <strong>Marksmen:</strong>
  <%= @event.marksmen %>
</p>

<p>
  <strong>Value:</strong>
  <%= @event.value %>
</p>

<p>
  <strong>Teiler:</strong>
  <%= @event.unknown7 %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time_date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Zurück', events_path %>