Rails/Projekte/shooting_club/config/routes.rb
Rails.application.routes.draw do
	

  get 'analysis/index'
  get 'analysis/select'
  get 'analysis/calculate'
  delete 'events/loeschen'
  delete 'events/loeschenall'

  resources :groups do
  	get 'addnew' => 'groups#addnew'
  	post 'addcreate' => 'groups#addcreate'
    delete 'deletem' => 'groups#deletem'
  end
	get 'auswertung' => 'events#indexwrong'
  resources :resumes
  resources :events do 
  	member do
  		get 'import'
  	end
 	end
 	root "marksmen#index"
 	resources :marksmen
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/Projekte/shooting_club/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @search = MarksmanGroup.where(group_id: @group.id)
    @list = []
    @search.each do |marksman|
      @list << Marksman.find_by(id: marksman.marksman_id)
    end
  end

  def deletem
    MarksmanGroup.find_by(marksman_id: params[:format].to_i, group_id: params[:group_id].to_i).destroy
    redirect_to group_url(params[:group_id]), notice: 'Der Member ist nicht mehr in der Gruppe.'
  end

  def addnew
    @member = MarksmanGroup.new
    @member.group_id = params[:group_id]
    @group = Group.find(params[:group_id])
  end

  def addcreate
    @member = MarksmanGroup.new
    @member.group_id = member_params[:group_id]
    if member_params[:marksman_id].to_i > 0 && Marksman.exists?(startnr: member_params[:marksman_id])
      @member.marksman_id = Marksman.find_by(startnr: member_params[:marksman_id]).id
      if !MarksmanGroup.exists?(:marksman_id => @member.marksman_id, :group_id => @member.group_id)
        respond_to do |format|
          if @member.save
            format.html { redirect_to group_path(@member.group_id), notice: 'Member was successfully added.' }
            format.json { render :show, status: :created, location: @group }
          else
            format.html { render :addnew }
            format.json { render json: @group.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to group_addnew_path(@member.group_id), alert: 'Member is already in this Group.'
      end
    else
      redirect_to group_addnew_path(@member.group_id), alert: 'Please enter an existing Marksman ID.'
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :note)
    end

    def member_params
      params.require(:marksman_group).permit(:marksman_id, :group_id)
    end
end

Rails/Projekte/shooting_club/app/views/groups/_addform.html.erb
<%= form_for(@member, :url => group_addcreate_path(@group.id)) do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="medium-4 columns">
    <%= f.hidden_field :group_id %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-4 columns">
    <%= f.label :marksman_id %>
    <%= f.text_field :marksman_id %>
    <br><br><br>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="actions medium-12 columns">
    <%= f.submit 'Abschicken', class: "button primary" %>
  </div>
</div>
<% end %>

Rails/Projekte/shooting_club/app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="medium-4 columns">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-4 columns">
    <%= f.label :note %>
    <%= f.text_field :note %>
    <br><br>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="actions medium-12 columns">
    <%= f.submit 'Abschicken', class: "button primary" %>
  </div>
</div>
<% end %>

Rails/Projekte/shooting_club/app/views/groups/addnew.html.erb
<p id="notice"><%= notice %></p>

<h1>Neues Mitglied:</h1>

<p class="label alert"><%= alert %></p>

<%= render 'addform', member: @member %>

<%= link_to 'Zurück', group_path(@group.id), class: "button small warning" %>

Rails/Projekte/shooting_club/app/views/groups/edit.html.erb
<h1>Gruppe editieren:</h1>

<%= render 'form', group: @group %>

<%= link_to 'Details', @group, class: "button small warning" %> |
<%= link_to 'Zurück', groups_path, class: "button small warning" %>

Rails/Projekte/shooting_club/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gruppen:</h1>
<br><br>

<div class="row">
  <div class="small-2 large-4 columns"><%= link_to 'Neue Gruppe', new_group_path, class: "button small primary" %></div>
  <div class="small-4 large-4 columns"></div>
  <div class="small-6 large-4 columns"></div>
</div>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.note %></td>
        <td>
          <%= link_to 'Details', group, class: "button small warning" %>
          <%= link_to 'Edit', edit_group_path(group), class: "button small secondary" %>
          <%= link_to 'Löschen', group, method: :delete, data: { confirm: 'Are you sure?' }, class: "button small alert" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

Rails/Projekte/shooting_club/app/views/groups/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Neue Gruppe:</h1>

<%= render 'form', group: @group %>

<%= link_to 'Zurück', groups_path, class: "button small warning" %>

Rails/Projekte/shooting_club/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Mitglied hinzufügen', group_addnew_path(@group.id), class: "button small primary" %>
<h4>
  <%= @group.name %>
</h4>

<p>
  <strong>Note:</strong>
  <%= @group.note %>
</p>

<p>
  <h4>Mitglieder:</h4>
  	<ul>
	  <% @list.each do |c| %>
	  	<li><%= "#{c.firstname} #{c.surname}" %> <%= link_to 'Löschen', group_deletem_path(@group.id, c.id), method: :delete, class: 'button alert' %></li>
	  <% end %>	
	</ul>
</p>


<%= link_to 'Edit', edit_group_path(@group), class: "button small secondary" %> |
<%= link_to 'Zurück', groups_path, class: "button small warning" %>