Rails/Projekte/shooting_club/config/routes.rb
Rails.application.routes.draw do
	

  get 'analysis/index'
  get 'analysis/select'
  get 'analysis/calculate'
  delete 'events/loeschen'
  delete 'events/loeschenall'

  resources :groups do
  	get 'addnew' => 'groups#addnew'
  	post 'addcreate' => 'groups#addcreate'
    delete 'deletem' => 'groups#deletem'
  end
	get 'auswertung' => 'events#indexwrong'
  resources :resumes
  resources :events do 
  	member do
  		get 'import'
  	end
 	end
 	root "marksmen#index"
 	resources :marksmen
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/Projekte/shooting_club/app/controllers/marksmen_controller.rb
class MarksmenController < ApplicationController
  before_action :set_marksman, only: [:show, :edit, :update, :destroy]

  # GET /marksmen
  # GET /marksmen.json
  def index
    if params[:sort] && params[:direction]
      @marksmen = Marksman.search(params[:search]).order(params[:sort] + " " + params[:direction]).paginate(:per_page => 20, :page => params[:page])
    else
      @marksmen = Marksman.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
    end
  end

  # GET /marksmen/1
  # GET /marksmen/1.json
  def show
    @search = MarksmanGroup.where(marksman_id: @marksman.id)
    @list = []
    @search.each do |group|
      @list << Group.find_by(id: group.group_id)
    end
  end

  # GET /marksmen/new
  def new
    @marksman = Marksman.new
  end

  # GET /marksmen/1/edit
  def edit
  end

  # POST /marksmen
  # POST /marksmen.json
  def create
    @marksman = Marksman.new(marksman_params)

    respond_to do |format|
      if @marksman.save
        format.html { redirect_to @marksman, notice: 'Marksman was successfully created.' }
        format.json { render :show, status: :created, location: @marksman }
      else
        format.html { render :new }
        format.json { render json: @marksman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marksmen/1
  # PATCH/PUT /marksmen/1.json
  def update
    respond_to do |format|
      if @marksman.update(marksman_params)
        format.html { redirect_to @marksman, notice: 'Marksman was successfully updated.' }
        format.json { render :show, status: :ok, location: @marksman }
      else
        format.html { render :edit }
        format.json { render json: @marksman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marksmen/1
  # DELETE /marksmen/1.json
  def destroy
    @marksman.destroy
    respond_to do |format|
      format.html { redirect_to marksmen_url, notice: 'Marksman was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marksman
      @marksman = Marksman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marksman_params
      params.require(:marksman).permit(:startnr, :firstname, :surname, :location)
    end


end

Rails/Projekte/shooting_club/app/views/marksmen/_form.html.erb
<%= form_for(marksman) do |f| %>
  <% if marksman.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marksman.errors.count, "error") %> prohibited this marksman from being saved:</h2>

      <ul>
      <% marksman.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="medium-4 columns">
    <%= f.label "Schützennummer" %>
    <%= f.number_field :startnr %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-4 columns">
    <%= f.label "Vorname" %>
    <%= f.text_field :firstname %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-4 columns">
    <%= f.label "Nachname" %>
    <%= f.text_field :surname %>
  </div>

  <div class="medium-12 columns">
  </div>

  <div class="medium-4 columns">
    <%= f.label "Ortschaft" %>
    <%= f.text_field :location %>
  </div>

  <div class="actions medium-12 columns">
    <%= f.submit 'Abschicken', class: "button primary" %>
  </div>
</div>
<% end %>

Rails/Projekte/shooting_club/app/views/marksmen/_marks.html.erb
<div class="row">
  <div class="large-3 columns">
    <%= link_to 'Neuer Schütze', new_marksman_path, method: :get, class: "button primary" %>
  </div>
  <div class="large-6 columns">
    <div class="digg_pagination margin_allgemein">
      <%= will_paginate @marksmen, :container => false %>
    </div>
  </div>
  <div class="large-3 columns">

  </div>
</div>

<br>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table>
  <thead>
    <tr>
      <th><%= sortable "startnr", "Schützennummer" %></th>
      <th><%= sortable "firstname", "Vorname" %></th>
      <th><%= sortable "surname", "Nachname" %></th>
      <th><%= sortable "location", "Ortschaft" %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @marksmen.each do |marksman| %>
      <tr>
        <td><%= marksman.startnr %></td>
        <td><%= marksman.firstname %></td>
        <td><%= marksman.surname %></td>
        <td><%= marksman.location %></td>
        <td>
          <%= link_to 'Details', marksman, class: "button small warning" %>
          <%= link_to 'Edit', edit_marksman_path(marksman), class: "button small secondary" %>
          <%= link_to 'Löschen', marksman, method: :delete, data: { confirm: 'Are you sure?' }, class: "button small alert" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @marksmen %>
  </div>
</div>

Rails/Projekte/shooting_club/app/views/marksmen/edit.html.erb
<h1>Editing Marksman</h1>

<%= render 'form', marksman: @marksman %>

<%= link_to 'Show', @marksman, class: "button small warning" %> |
<%= link_to 'Back', marksmen_path, class: "button small warning" %>

Rails/Projekte/shooting_club/app/views/marksmen/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schützentabelle</h1>
<br><br>

<%= form_tag marksmen_path, :method => 'get', :id => "marks_search" do %>

  <div class="input-group anzeige">
  <span class="input-group-label">Suche:</span>
  <%= text_field_tag :search, params[:search], :class => "input-group-field" %>
  <div class="input-group-button">
    <%= submit_tag "Search", :name => nil, :class => "button invisible" %>
  </div>
</div>
  <div id="marks"><%= render 'marks' %></div>
<% end %>
<br>
</div>

Rails/Projekte/shooting_club/app/views/marksmen/index.js.erb
$("#marks").html("<%= escape_javascript(render("marks")) %>");

Rails/Projekte/shooting_club/app/views/marksmen/new.html.erb
<h1>New Marksman</h1>

<%= render 'form', marksman: @marksman %>

<%= link_to 'Back', marksmen_path, class: "button small warning" %>

Rails/Projekte/shooting_club/app/views/marksmen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Schützennummer:</strong>
  <%= @marksman.startnr %>
</p>

<p>
  <strong>Vorname:</strong>
  <%= @marksman.firstname %>
</p>

<p>
  <strong>Nachname:</strong>
  <%= @marksman.surname %>
</p>

<p>
  <strong>Ortschaft:</strong>
  <%= @marksman.location %>
</p>

<p>
  <h4>Gruppenangehörigkeit:</h4>
  	<ul>
	  <% @list.each do |c| %>
	  	<li><%= "#{c.name}" %></li>
	  <% end %>	
	</ul>
</p>

<%= link_to 'Edit', edit_marksman_path(@marksman), class: "button small secondary" %> 
<%= link_to 'Zurück', marksmen_path, class: "button small warning" %>